apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: zfw-dev
spec:
  secretStoreRef:
    name: doppler-dev
    kind: ClusterSecretStore
  target:
    name: api-secrets
  dataFrom:
  - find:
      name:
        regexp: .*