mysql:
  auth:
    username: zfw
    database: zfw
    existingSecret: passwords
  primary:
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1024Mi
        cpu: 250m
    persistence:
      size: 25Gi
