mysql:
  auth:
    username: zfw
    database: zfw
    existingSecret: passwords
  primary:
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 1024Mi
    persistence:
      size: 15Gi
