apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: "wm@zfwartcc.net"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-api-token
            key: api-token
