apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    name: doppler-cluster-prod
    kind: ClusterSecretStore
  target:
    name: digitalocean-api-token
  data:
  - secretKey: token
    remoteRef:
      key: DO_API_TOKEN