ingress-nginx:
  controller:
    kind: DaemonSet
    config:
      allow-snippet-annotations: "true"
      compute-full-forwarded-for: "true"
      proxy-body-size: 128m
      use-forwarded-headers: "true"
      use-proxy-protocol: "false"
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "false"
        service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"