apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-denartcc-org-tls
spec:
  dnsNames:
  - www.zfwartcc.net
  - zfwartcc.net
  - new.zfwartcc.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-denartcc-org-tls
