apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-zfwartcc-net-tls
spec:
  dnsNames:
    - www.zfwartcc.net
    - zfwartcc.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-zfwartcc-net-tls
