apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
- discord/certificate.yaml
- discord/deployment.yaml
- discord/ingress.yaml
- discord/service.yaml
- chart-parser/cronjob.yaml
images:
- name: adhp/auth
  newName: adhp/auth
  newTag: 72032a6
- name: adhp/frontend
  newName: adhp/frontend
  newTag: zfw-v1.9.1734393661.80-d8eeed4
- name: denartcc/api
  newName: adhp/api
  newTag: main-8714ede
