apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
- discord/certificate.yaml
- discord/deployment.yaml
- discord/ingress.yaml
- discord/service.yaml
- chart-parser/cronjob.yaml
- ids/certificate.yaml
- ids/configmap.yaml
- ids/deployment-backend.yaml
- ids/deployment-frontend.yaml
- ids/ingress.yaml
- ids/service-backend.yaml
- ids/service-frontend.yaml
images:
- name: adhp/auth
  newName: adhp/auth
  newTag: 72032a6
- name: adhp/frontend
  newName: adhp/frontend
  newTag: zfw-v1.9.1734395786.81-9ce18b5
- name: adhp/ids-backend
  newName: docker.io/adhp/ids-backend
  newTag: zfw-main-8965a26
- name: adhp/ids-frontend
  newName: docker.io/adhp/ids-frontend
  newTag: zfw-main-8965a26
- name: denartcc/api
  newName: adhp/api
  newTag: main-8714ede
