apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-backup-credentials
  namespace: mysql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-prod
  
  target:
    name: mysql-backup-credentials
  
  data:
    - secretKey: AWS_ACCESS_KEY
      remoteRef:
        key: BACKUP_AWS_ACCESS_KEY
    - secretKey: AWS_SECRET_KEY
      remoteRef:
        key: BACKUP_AWS_SECRET_KEY
    - secretKey: AWS_ENDPOINT
      remoteRef:
        key: BACKUP_AWS_ENDPOINT
    - secretKey: AWS_BUCKET
      remoteRef:
        key: BACKUP_AWS_BUCKET
    - secretKey: MYSQL_HOST
      remoteRef:
        key: BACKUP_MYSQL_HOST
    - secretKey: MYSQL_USER
      remoteRef:
        key: BACKUP_MYSQL_USER
    - secretKey: MYSQL_PWD
      remoteRef:
        key: BACKUP_MYSQL_PASSWORD