apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secrets
  namespace: zfw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-prod
  
  target:
    name: auth-secrets

  dataFrom:
  - find:
      name:
        regexp: .*